### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by n-ogino** [JuanitoFatas/what-do-you-call-this-in-ruby#43]
#IPアドレス
18.180.216.179
よろしくお願いします。

**Comment by yasunamiura** [comment]
荻野さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
①IPアドレスにアクセスするとエラー画面になってしまう
<img width="1287" alt="Test_Page_for_the_Nginx_HTTP_Server_on_the_Amazon_Linux_AMI" src="https://user-images.githubusercontent.com/52514431/80774708-b4090000-8b98-11ea-8879-1423d60aad2e.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by n-ogino** [comment]
修正しました。
今度こそ、ご確認をお願いします。

**Comment by yasunamiura** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①最新メッセージもこの線が先頭になるようにしましょう**
<img width="800" alt="ChatSpace" src="https://user-images.githubusercontent.com/52514431/80789181-29d79080-8bc6-11ea-9fc2-9ea961e7175f.png">

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by n-ogino** [comment]
修正内容を確認し、修正しました。
再度、ご確認をお願いします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、前回の指摘事項の修正が確認できませんでした。
デプロイはお済みでしょうか？
うまくいっていない可能性もありますので、ご確認宜しくお願いいたします！

[修正箇所]
https://github.com/JuanitoFatas/what-do-you-call-this-in-ruby/issues/43#issuecomment-622278683

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by n-ogino** [comment]
すみません、デプロイを忘れておりました。
今度こそ、お願いします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by n-ogino** [comment]
ありがとうございました！
ご面倒をおかけしました。
